/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_android_bluetoothlegatt_MyNative */

#ifndef _Included_com_example_android_bluetoothlegatt_MyNative
#define _Included_com_example_android_bluetoothlegatt_MyNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_android_bluetoothlegatt_MyNative
 * Method:    update_fileParse
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_example_android_bluetoothlegatt_MyNative_update_1fileParse
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_example_android_bluetoothlegatt_MyNative
 * Method:    update_checkSetFlag
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_android_bluetoothlegatt_MyNative_update_1checkSetFlag
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_android_bluetoothlegatt_MyNative
 * Method:    update_getImageInfo
 * Signature: (I[B[B[B[B[B)I
 */
JNIEXPORT jint JNICALL Java_com_example_android_bluetoothlegatt_MyNative_update_1getImageInfo
  (JNIEnv *, jobject, jint, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_example_android_bluetoothlegatt_MyNative
 * Method:    wavemake
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_example_android_bluetoothlegatt_MyNative_wavemake
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_example_android_bluetoothlegatt_MyNative
 * Method:    audioInterface
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_example_android_bluetoothlegatt_MyNative_audioInterface
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_example_android_bluetoothlegatt_MyNative
 * Method:    cToJava
 * Signature: ([BI[B)I
 */
JNIEXPORT jint JNICALL Java_com_example_android_bluetoothlegatt_MyNative_cToJava
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
